from __future__ import annotations

import re
from datetime import datetime, timezone
from io import StringIO
from pathlib import Path

from aigov.core.models import AISystemRecord, RiskLevel

# Tags that may carry redacted credential material — never write to docs.
_SENSITIVE_TAGS = frozenset({"key_preview", "key_type"})


def _slug(name: str) -> str:
    """Filesystem-safe slug, max 60 chars."""
    return re.sub(r'[^\w]+', '_', name.lower()).strip('_')[:60]


def _source_slug(record: AISystemRecord) -> str:
    """Derive a slug from the source file stem (e.g. 'fraud_detection' from
    'demo\\analytics\\fraud_detection.py:2').  Falls back to _slug(record.name)
    when source_location contains no recognisable file name."""
    loc = record.source_location
    # Strip trailing line-number annotation (e.g. ":42" or "#L42")
    loc = re.sub(r'[:#]L?\d+$', '', loc)
    # Split on both / and \ so Windows-style paths work on Linux runners too.
    parts = re.split(r'[/\\]', loc)
    filename = next((p for p in reversed(parts) if p), '')
    stem = Path(filename).stem if filename else ''
    if stem and stem not in ('.', ''):
        return _slug(stem)
    return _slug(record.name)


def _unique_slug(base: str, used: dict[str, int]) -> str:
    if base not in used:
        used[base] = 1
        return base
    used[base] += 1
    return f"{base}_{used[base]}"


def _safe_tags(record: AISystemRecord) -> dict[str, str]:
    """Return tags with sensitive keys stripped."""
    return {k: v for k, v in record.tags.items() if k not in _SENSITIVE_TAGS}


def _ts(record: AISystemRecord) -> str:
    return record.discovery_timestamp.strftime("%Y-%m-%d")


def _generated_header(doc_type: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"*Generated by aigov on {now}*  \n"
        f"*{doc_type} — requires human review and completion before submission*\n\n"
        "---\n\n"
    )


# ---------------------------------------------------------------------------
# Annex IV template (HIGH_RISK)
# ---------------------------------------------------------------------------

def _annex_iv(record: AISystemRecord) -> str:
    buf = StringIO()
    w = buf.write
    tags = _safe_tags(record)
    category = tags.get("eu_ai_act_category", "Not determined")
    article = tags.get("eu_ai_act_article", "Annex III")
    model_id = record.model_identifier or "Not specified"
    rationale = record.classification_rationale or "Not available"

    w(f"# Annex IV Technical Documentation: {record.name}\n\n")
    w("**EU AI Act — Article 11 & Annex IV Technical Documentation**  \n")
    w(_generated_header("DRAFT"))

    # ── Section 1 ──────────────────────────────────────────────────────────
    w("## 1. General Description of the AI System\n\n")
    w("*Article 11 and Annex IV §1 require a general description of the AI system.*\n\n")
    w("| Field | Value |\n|-------|-------|\n")
    w(f"| System Name | {record.name} |\n")
    w(f"| Provider | {record.provider} |\n")
    w(f"| Model Identifier | {model_id} |\n")
    w(f"| Deployment Type | {record.deployment_type.value} |\n")
    w(f"| Source Location | `{record.source_location}` |\n")
    w(f"| Discovery Date | {_ts(record)} |\n")
    w(f"| Risk Classification | HIGH RISK (Annex III) |\n")
    w(f"| EU AI Act Category | {category} |\n")
    w(f"| Regulatory Reference | {article} |\n")
    w(f"| Scanner | {record.source_scanner} |\n\n")
    w("**Classification rationale (from aigov):**  \n")
    w(f"{rationale}\n\n")
    w("---\n\n")

    # ── Section 2 ──────────────────────────────────────────────────────────
    w("## 2. Detailed Description of Elements and Development Process\n\n")
    w("*Annex IV §2 requires a detailed description of system elements and the development process.*\n\n")

    w("### 2.1 Intended Purpose\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the specific intended purpose of the AI system, including: the domain of "
        "application, the specific task performed, the intended deployers and affected persons, "
        "and geographic scope. Article 9 and Article 13(3)(a) require this to be unambiguous.*\n\n"
    )
    w("**Intended Purpose:**  \n[FILL IN]\n\n")
    w("**Target Users / Deployers:**  \n[FILL IN]\n\n")
    w("**Affected Persons:**  \n[FILL IN]\n\n")

    w("### 2.2 Input and Output Data Types\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the types of data the system ingests (e.g., text, images, structured records, "
        "biometric data) and the form of its outputs (e.g., scores, decisions, ranked lists, "
        "generated text). Specify any personal or sensitive data categories processed.*\n\n"
    )
    w("**Input Data:**  \n[FILL IN]\n\n")
    w("**Output Data:**  \n[FILL IN]\n\n")
    if record.data_categories:
        w(f"**Data categories detected by scanner:** {', '.join(record.data_categories)}  \n\n")

    w("### 2.3 AI Techniques and Approaches\n\n")
    w("**Status: Partially pre-filled — verify and expand**\n\n")
    w(f"**Provider:** {record.provider}  \n")
    w(f"**Scanner detected via:** {record.source_scanner}  \n")
    if model_id != "Not specified":
        w(f"**Model identifier:** {model_id}  \n")
    w("\n")
    w(
        "*Describe the AI techniques used (e.g., supervised learning, transformer-based LLM, "
        "reinforcement learning), the model architecture, and any third-party components or "
        "foundation models relied upon.*\n\n"
    )
    w("**Architecture / Technique:**  \n[FILL IN]\n\n")
    w("**Third-party components:**  \n[FILL IN]\n\n")

    w("### 2.4 Computational Resources\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the hardware, cloud infrastructure, and compute requirements. "
        "Specify whether the system runs on dedicated hardware, shared cloud infrastructure, "
        f"or edge devices. Deployment type detected: **{record.deployment_type.value}**.*\n\n"
    )
    w("**Infrastructure:**  \n[FILL IN]\n\n")
    w("---\n\n")

    # ── Section 3 ──────────────────────────────────────────────────────────
    w("## 3. Monitoring, Logging, and Control Measures\n\n")
    w("*Article 12 requires automatic logging. Article 14 requires effective human oversight.*\n\n")

    w("### 3.1 Logging Mechanisms (Article 12)\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Article 12 requires high-risk AI systems to automatically log events throughout their "
        "operation. Logs must enable traceability, including: input data characteristics, "
        "operation periods (start/end timestamps), reference database used (if applicable), "
        "and any circumstances that led to results requiring human review.*\n\n"
    )
    w("**Logging Implementation:**  \n[FILL IN]\n\n")
    w("**Log Retention Period:**  \n[FILL IN]\n\n")
    w("**Log Access Controls:**  \n[FILL IN]\n\n")

    w("### 3.2 Human Oversight Design (Article 14)\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Article 14 requires high-risk AI systems to be designed to allow effective human "
        "oversight. The system must: (a) be identifiable and interpretable by operators; "
        "(b) allow operators to disregard, override, or reverse outputs; "
        "(c) include a stop button or equivalent cessation mechanism; "
        "(d) be monitored by assigned natural persons.*\n\n"
    )
    w("**Oversight Mechanism:**  \n[FILL IN]\n\n")
    w("**Override / Stop Capability:**  \n[FILL IN]\n\n")
    w("**Assigned Oversight Role:**  \n[FILL IN]\n\n")

    w("### 3.3 Performance Metrics and Monitoring\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Define the KPIs used to monitor system performance in production. "
        "Include thresholds that trigger human review or system suspension. "
        "Specify monitoring cadence (real-time, daily, per-batch).*\n\n"
    )
    w("**Performance KPIs:**  \n[FILL IN]\n\n")
    w("**Alert Thresholds:**  \n[FILL IN]\n\n")
    w("---\n\n")

    # ── Section 4 ──────────────────────────────────────────────────────────
    w("## 4. Risk Management System\n\n")
    w("*Article 9 requires a documented, iterative risk management system.*\n\n")

    w("### 4.1 Risk Identification\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Article 9(2) requires identification and analysis of all reasonably foreseeable risks "
        "associated with the AI system, including risks to health, safety, and fundamental rights. "
        "Consider risks from: misuse, unintended use, interaction with other systems, and "
        "data quality issues.*\n\n"
    )
    w("**Identified Risks:**  \n[FILL IN]\n\n")

    w("### 4.2 Risk Mitigation Measures\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*For each identified risk, describe the mitigation measure adopted and the residual risk "
        "level after mitigation. Article 9(4) requires that risk management measures give "
        "due consideration to the effects on children and other vulnerable groups.*\n\n"
    )
    w("| Risk | Mitigation Measure | Residual Risk |\n|------|-------------------|---------------|\n")
    w("| [FILL IN] | [FILL IN] | [FILL IN] |\n\n")

    w("### 4.3 Residual Risks\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*List any residual risks that remain after mitigation, and explain why they are "
        "acceptable. Article 9(6) requires that residual risks communicated to users.*\n\n"
    )
    w("**Residual Risks:**  \n[FILL IN]\n\n")
    w("---\n\n")

    # ── Section 5 ──────────────────────────────────────────────────────────
    w("## 5. Data Governance\n\n")
    w("*Article 10 requires training, validation, and testing data to meet quality criteria.*\n\n")

    w("### 5.1 Training Data Description\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the datasets used for training, validation, and testing. Include: data source, "
        "collection methodology, geographic scope, time period, and any known limitations. "
        "Article 10(3) requires datasets to be relevant, representative, and free of errors.*\n\n"
    )
    w("**Training Data:**  \n[FILL IN]\n\n")
    w("**Validation Data:**  \n[FILL IN]\n\n")
    w("**Test Data:**  \n[FILL IN]\n\n")

    w("### 5.2 Data Quality Measures\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the data quality checks applied before and during training. "
        "Include data cleaning procedures, quality metrics, and how data quality is maintained "
        "over the system's operational lifetime.*\n\n"
    )
    w("**Quality Checks Applied:**  \n[FILL IN]\n\n")

    w("### 5.3 Bias Assessment and Mitigation\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Article 10(2)(f) requires datasets to be examined for possible biases. "
        "Describe: the bias metrics used, protected characteristics examined (e.g., age, gender, "
        "ethnicity, disability), testing methodology, and corrective measures taken.*\n\n"
    )
    w("**Bias Metrics Used:**  \n[FILL IN]\n\n")
    w("**Protected Characteristics Examined:**  \n[FILL IN]\n\n")
    w("**Corrective Measures:**  \n[FILL IN]\n\n")
    w("---\n\n")

    # ── Section 6 ──────────────────────────────────────────────────────────
    w("## 6. Accuracy, Robustness, and Cybersecurity\n\n")
    w("*Article 15 requires appropriate levels of accuracy, robustness, and cybersecurity.*\n\n")

    w("### 6.1 Accuracy Metrics\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Specify the accuracy metric(s) appropriate for this system's task (e.g., F1 score, "
        "AUC-ROC, precision/recall, calibration error). Provide benchmark results from "
        "validation and test sets. Article 15(1) requires the system to achieve the accuracy "
        "level declared in the technical documentation.*\n\n"
    )
    w("**Accuracy Metric:** [FILL IN]  \n")
    w("**Benchmark Result:** [FILL IN]  \n")
    w("**Acceptable Threshold:** [FILL IN]  \n\n")

    w("### 6.2 Robustness Testing\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe tests conducted for robustness against: adversarial inputs, "
        "out-of-distribution data, data drift, and edge cases. Article 15(4) requires "
        "resilience against attempts to alter system use or performance by third parties.*\n\n"
    )
    w("**Robustness Tests Conducted:**  \n[FILL IN]\n\n")

    w("### 6.3 Cybersecurity Measures\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe the cybersecurity controls protecting the AI system and its data. "
        "Include: access controls, encryption at rest and in transit, vulnerability management, "
        "and incident response procedures.*\n\n"
    )
    w("**Cybersecurity Controls:**  \n[FILL IN]\n\n")
    w("---\n\n")

    # ── Section 7 ──────────────────────────────────────────────────────────
    w("## 7. Conformity Assessment\n\n")
    w("*Article 43 requires a conformity assessment before market placement.*\n\n")
    w("**Status: TODO**\n\n")
    w(
        f"*The system falls under Annex III category: **{category}**. "
        "Determine the applicable conformity assessment route:*\n\n"
        "*- **Self-assessment (Annex VI):** Available for most Annex III categories where "
        "the provider applies harmonised standards or common specifications.*  \n"
        "*- **Third-party assessment by notified body (Annex VII):** Required for AI systems "
        "used in biometric identification, or where the provider has not applied harmonised "
        "standards covering all relevant requirements.*\n\n"
        "*After assessment: compile the EU Declaration of Conformity (Annex V) and affix CE "
        "marking where required.*\n\n"
    )
    w("**Assessment Route Selected:** [FILL IN — self-assessment / notified body]  \n")
    w("**Notified Body (if applicable):** [FILL IN]  \n")
    w("**Assessment Start Date:** [FILL IN]  \n")
    w("**Target Completion Date:** [FILL IN — must be before 2026-08-02]  \n")
    w("**CE Marking Required:** [FILL IN — Yes / No]  \n\n")
    w("---\n\n")

    # ── Section 8 ──────────────────────────────────────────────────────────
    w("## 8. EU Database Registration\n\n")
    w("*Article 49 requires registration in the EU AI database before market placement.*\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Providers of high-risk AI systems must register in the EU-wide AI database "
        "operated by the European Commission before placing the system on the market. "
        "Registration requires information per Annex VIII, including: provider identity, "
        "system name and version, intended purpose, risk classification, and conformity "
        "assessment details.*\n\n"
    )
    w("**Registration Status:** [ ] Not started  [ ] In progress  [ ] Registered  \n")
    w("**EU Database Entry ID:** [FILL IN once registered]  \n")
    w("**Registration Date:** [FILL IN]  \n")
    w("**Annex VIII Information Compiled:** [ ] Yes  [ ] No  \n\n")
    w("---\n\n")
    w("*End of Annex IV Technical Documentation Template*\n")

    return buf.getvalue()


# ---------------------------------------------------------------------------
# Transparency template (LIMITED_RISK)
# ---------------------------------------------------------------------------

def _transparency_doc(record: AISystemRecord) -> str:
    buf = StringIO()
    w = buf.write
    tags = _safe_tags(record)
    category = tags.get("eu_ai_act_category", "Not determined")
    rationale = record.classification_rationale or "Not available"

    w(f"# Article 50 Transparency Obligations: {record.name}\n\n")
    w("**EU AI Act — Article 50 Transparency Obligations**  \n")
    w(_generated_header("DRAFT"))

    w("## System Description\n\n")
    w("| Field | Value |\n|-------|-------|\n")
    w(f"| System Name | {record.name} |\n")
    w(f"| Provider | {record.provider} |\n")
    w(f"| Deployment Type | {record.deployment_type.value} |\n")
    w(f"| Source Location | `{record.source_location}` |\n")
    w(f"| Discovery Date | {_ts(record)} |\n")
    w(f"| Risk Classification | LIMITED RISK |\n")
    w(f"| EU AI Act Category | {category} |\n")
    if record.model_identifier:
        w(f"| Model Identifier | {record.model_identifier} |\n")
    w("\n")
    w("**Classification rationale (from aigov):**  \n")
    w(f"{rationale}\n\n")
    w("---\n\n")

    w("## Article 50 Requirements\n\n")
    w(
        "Article 50 of the EU AI Act imposes transparency obligations on providers and "
        "deployers of certain AI systems. The following requirements apply:\n\n"
    )
    w(
        "**Article 50(1) — AI interaction disclosure:** Providers of AI systems intended "
        "to interact directly with natural persons must ensure those persons are informed "
        "they are interacting with an AI system, unless this is obvious from context.\n\n"
    )
    w(
        "**Article 50(4) — Synthetic content labeling:** Providers of AI systems that "
        "generate or manipulate image, audio, video, or text content (including deepfakes) "
        "must ensure outputs are marked as artificially generated or manipulated, using "
        "machine-readable formats.\n\n"
    )
    w("---\n\n")

    w("## Transparency Measures Checklist\n\n")
    w(
        "*Complete this checklist and retain as evidence of compliance. "
        "Each item must be implemented before the system is deployed to end users.*\n\n"
    )

    w("### AI Interaction Disclosure (Article 50(1))\n\n")
    w("- [ ] Users are notified at the start of every AI-mediated interaction\n")
    w("- [ ] Disclosure is clear, prominent, and in plain language\n")
    w("- [ ] Disclosure appears before the interaction begins (not buried in T&Cs)\n")
    w("- [ ] The disclosure mechanism has been reviewed by legal counsel\n")
    w("- [ ] Exception reviewed: is the AI nature obvious from context? (document justification if yes)\n\n")

    w("### Synthetic Content Labeling (Article 50(4))\n\n")
    w("- [ ] All AI-generated content (text, images, audio, video) is labeled\n")
    w("- [ ] Labels are machine-readable (e.g., C2PA metadata, watermarks)\n")
    w("- [ ] Labels are human-readable where content is consumed by people\n")
    w("- [ ] Labels persist through download, sharing, and republication\n")
    w("- [ ] Labeling coverage has been tested end-to-end\n\n")

    w("### Documentation and Record-Keeping\n\n")
    w("- [ ] Disclosure mechanism is documented in technical documentation\n")
    w("- [ ] Evidence of disclosure implementation is retained\n")
    w("- [ ] Responsible person / team assigned for ongoing compliance\n")
    w("- [ ] Review scheduled before 2026-08-02 (EU AI Act application deadline)\n\n")

    w("---\n\n")
    w("## Implementation Notes\n\n")
    w("**Status: TODO**\n\n")
    w(
        "*Describe how the transparency requirements are or will be implemented "
        "in this specific system. Include: the disclosure text used, where it appears in the "
        "user journey, and how synthetic content is labeled.*\n\n"
    )
    w("**Disclosure Text / Mechanism:**  \n[FILL IN]\n\n")
    w("**Content Labeling Approach:**  \n[FILL IN]\n\n")
    w("**Implementation Owner:**  \n[FILL IN]\n\n")
    w("**Target Completion Date:**  \n[FILL IN]\n\n")
    w("---\n\n")
    w("*End of Article 50 Transparency Obligations Document*\n")

    return buf.getvalue()


# ---------------------------------------------------------------------------
# Prohibited notice (PROHIBITED)
# ---------------------------------------------------------------------------

def _prohibited_doc(record: AISystemRecord) -> str:
    buf = StringIO()
    w = buf.write
    tags = _safe_tags(record)
    category = tags.get("eu_ai_act_category", "Not determined")
    article = tags.get("eu_ai_act_article", "Article 5")
    rationale = record.classification_rationale or "Not available"

    w(f"# PROHIBITED AI System Notice: {record.name}\n\n")
    w("**EU AI Act — Article 5 Prohibited Practice**  \n")
    w("**:warning: IMMEDIATE ACTION REQUIRED :warning:**  \n")
    w(_generated_header("COMPLIANCE NOTICE"))

    w("## System Identified\n\n")
    w("| Field | Value |\n|-------|-------|\n")
    w(f"| System Name | {record.name} |\n")
    w(f"| Provider | {record.provider} |\n")
    w(f"| Deployment Type | {record.deployment_type.value} |\n")
    w(f"| Source Location | `{record.source_location}` |\n")
    w(f"| Discovery Date | {_ts(record)} |\n")
    w(f"| Risk Classification | **PROHIBITED** |\n")
    w(f"| Article 5 Category | {category} |\n")
    w(f"| Regulatory Reference | {article} |\n\n")
    w("---\n\n")

    w("## Prohibited Practice\n\n")
    w(
        "This AI system has been classified as a **prohibited practice** under Article 5 "
        "of the EU AI Act. Article 5 sets out absolute prohibitions — AI practices in this "
        "category may **not** be placed on the market, put into service, or used in the EU, "
        "regardless of any mitigations applied.\n\n"
    )
    w(f"**Identified prohibited practice:** {category}  \n")
    w(f"**Regulatory reference:** {article}  \n\n")
    w("**Classification rationale (from aigov):**  \n")
    w(f"{rationale}\n\n")
    w(
        "> **Legal note:** Article 5 prohibitions are not subject to a risk-based "
        "balancing test. If this classification is confirmed by legal counsel, there is "
        "no compliant path to deployment within the EU.\n\n"
    )
    w("---\n\n")

    w("## Required Immediate Actions\n\n")
    w(
        "The following actions must be taken **immediately** upon confirmation of this "
        "classification. Do not wait for the 2026-08-02 deadline — Article 5 applies from "
        "the date of EU AI Act enforcement.\n\n"
    )
    w("- [ ] **Suspend all deployment and operation** of this AI system immediately\n")
    w("- [ ] **Notify senior leadership and legal counsel** of the prohibited classification\n")
    w("- [ ] **Engage qualified EU AI Act legal advice** to confirm or contest the classification\n")
    w("- [ ] **Document the cessation decision** with date, authorising person, and scope\n")
    w("- [ ] **Notify affected deployers or customers** if the system has been distributed\n")
    w("- [ ] **Preserve all system records** — do not delete models, logs, or training data\n\n")
    w("---\n\n")

    w("## Remediation Guidance\n\n")
    w(
        "If legal review **confirms** the prohibition, the system must be decommissioned "
        "and not re-deployed in the EU. Consider:\n\n"
    )
    w(
        "- Redesigning the system to remove the prohibited capability and re-classifying "
        "under the risk framework\n"
    )
    w("- Restricting deployment to jurisdictions outside the EU where the practice is permitted\n")
    w("- Replacing the system with a compliant alternative\n\n")
    w(
        "If legal review **contests** the classification (e.g., aigov produced a false positive), "
        "document the legal basis for continued operation and retain this review as evidence "
        "of due diligence.\n\n"
    )

    w("**Legal review outcome:**  \n[ ] Confirmed prohibited — decommissioning in progress  \n")
    w("[ ] Classification contested — legal justification attached  \n\n")
    w("**Review date:**  \n[FILL IN]\n\n")
    w("**Reviewing counsel / firm:**  \n[FILL IN]\n\n")
    w("---\n\n")
    w("*End of Article 5 Prohibited Practice Notice*\n")

    return buf.getvalue()


# ---------------------------------------------------------------------------
# Index
# ---------------------------------------------------------------------------

def _index_doc(
    entries: list[dict],
    all_records: list[AISystemRecord],
    generated_at: str,
) -> str:
    buf = StringIO()
    w = buf.write

    w("# aigov Compliance Documentation Index\n\n")
    w("**EU AI Act Compliance Documentation**  \n")
    w(f"*Generated by aigov on {generated_at}*\n\n")
    w("---\n\n")

    w("## Generated Documents\n\n")
    if not entries:
        w("*No compliance documents were generated. All systems are MINIMAL RISK.*\n\n")
    else:
        w("| System | Risk Level | Document Type | File | Status |\n")
        w("|--------|-----------|---------------|------|--------|\n")
        for entry in entries:
            rec = entry["record"]
            risk = (rec.risk_classification.value.upper().replace("_", " ")
                    if rec.risk_classification else "UNKNOWN")
            fname = Path(entry["path"]).name
            doc_type = entry["doc_type"]
            w(f"| {rec.name} | {risk} | {doc_type} | [{fname}]({fname}) | DRAFT — requires completion |\n")
        w("\n")

    # List MINIMAL_RISK / unclassified systems that got no docs
    no_doc_records = [
        r for r in all_records
        if not any(e["record"] is r for e in entries)
    ]
    if no_doc_records:
        w("## Systems Requiring No Documentation\n\n")
        w(
            "The following systems were classified as MINIMAL RISK or could not be classified "
            "and do not require EU AI Act compliance documentation:\n\n"
        )
        w("| System | Provider | Risk Level | Location |\n")
        w("|--------|----------|-----------|----------|\n")
        for rec in no_doc_records:
            risk = (rec.risk_classification.value.upper().replace("_", " ")
                    if rec.risk_classification else "UNKNOWN")
            w(f"| {rec.name} | {rec.provider} | {risk} | `{rec.source_location}` |\n")
        w("\n")

    w("---\n\n")
    w("## Next Steps\n\n")
    w("1. Review each DRAFT document and complete all `[FILL IN]` and `TODO` sections\n")
    w("2. Engage legal counsel to confirm risk classifications\n")
    w("3. For HIGH RISK systems: complete conformity assessment before **2026-08-02**\n")
    w("4. For PROHIBITED systems: take immediate action — see the notice document\n")
    w("5. Register all HIGH RISK systems in the EU AI database (Article 49)\n")
    w("6. Re-run `aigov scan` periodically to detect newly added AI systems\n")

    return buf.getvalue()


# ---------------------------------------------------------------------------
# DocsGenerator
# ---------------------------------------------------------------------------

class DocsGenerator:
    def generate(self, records: list[AISystemRecord], output_dir: str) -> list[str]:
        """Generate EU AI Act compliance documents for classified AI systems.

        Returns a list of file paths created (relative to output_dir).
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        created: list[str] = []
        entries: list[dict] = []
        used_slugs: dict[str, int] = {}

        for record in records:
            risk = record.risk_classification or RiskLevel.UNKNOWN
            slug = _unique_slug(_source_slug(record), used_slugs)

            if risk == RiskLevel.HIGH_RISK:
                fname = f"{slug}_annex_iv.md"
                content = _annex_iv(record)
                doc_type = "Annex IV Technical Documentation"
            elif risk == RiskLevel.LIMITED_RISK:
                fname = f"{slug}_transparency.md"
                content = _transparency_doc(record)
                doc_type = "Article 50 Transparency Obligations"
            elif risk == RiskLevel.PROHIBITED:
                fname = f"{slug}_prohibited.md"
                content = _prohibited_doc(record)
                doc_type = "Article 5 Prohibited Practice Notice"
            else:
                continue

            path = out / fname
            path.write_text(content, encoding="utf-8")
            full_path = str(path)
            created.append(full_path)
            entries.append({"record": record, "path": full_path, "doc_type": doc_type})

        index_content = _index_doc(entries, records, generated_at)
        index_path = out / "index.md"
        index_path.write_text(index_content, encoding="utf-8")
        created.append(str(index_path))

        return created
